#!/bin/bash
# @autor SandroRybarik

# Program emulates communication client-server with help
# of unix programs.
# Warning: Program is not suitable for production use!

# port, where we send our data
port=1234

nc 127.0.0.1 $port

# Opens connection with our "server" program, which listens
# at 127.0.0.1 port 1234
# Now after typing into terminal window, data will be shown 
# at server terminal window


#----------------------------------------------------
#  FOR MORE INFORMATION TYPE INTO TERMINAL : man nc |
#----------------------------------------------------
